export { default as RegisterForm } from "./RegisterForm"
export { default as Welcome } from "./Welcome"
export { default as Navbar } from "./Navbar"
export { default as Public } from './Public'
export { default as Home } from './Home'
export { default as Posts } from './Posts'
export { default as Profile } from './Profile'
export { default as DetailPost } from './DetailPost'
export { default as CreatePost } from './CreatePost'
export { default as EditPost } from './EditPost'
export { default as Login } from './Login'
